-- Creación de la base de datos
CREATE DATABASE IF NOT EXISTS recetas_db;
USE recetas_db;

-- Tabla para las categorías de las recetas
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    nombre_categoria VARCHAR(100) UNIQUE
);

-- Tabla para los ingredientes
CREATE TABLE INGREDIENTES (
    ID_INGREDIENTE INT PRIMARY KEY AUTO_INCREMENT,
    nombre_ingrediente VARCHAR(100) UNIQUE
);

-- Tabla para las recetas
CREATE TABLE RECETAS (
    ID_RECETA INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255),
    instrucciones TEXT,
    tiempo_preparacion INT,
    dificultad VARCHAR(50),
    ID_CATEGORIA INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

-- Tabla de unión para la relación entre recetas e ingredientes
CREATE TABLE RECETAS_INGREDIENTES (
    ID_RECETA INT,
    ID_INGREDIENTE INT,
    cantidad VARCHAR(50),
    PRIMARY KEY (ID_RECETA, ID_INGREDIENTE),
    FOREIGN KEY (ID_RECETA) REFERENCES RECETAS(ID_RECETA),
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID_INGREDIENTE)
);

-- Inserción de datos: 5 categorías, 100 ingredientes y 100 recetas.
-- Esto asegura una base de datos con más de 200 registros en total.

-- 1. Datos para la tabla CATEGORIAS (5 registros)
INSERT INTO CATEGORIAS (nombre_categoria) VALUES
('Rápidas'),
('Saludables'),
('Postres'),
('Comida casera'),
('Desayunos');

-- 2. Datos para la tabla INGREDIENTES (100 registros)
INSERT INTO INGREDIENTES (nombre_ingrediente) VALUES
('Pasta'), ('Pesto'), ('Tomates cherry'), ('Queso rallado'), ('Quinoa'), ('Pepino'), ('Tomate'), ('Cebolla roja'), ('Limón'), ('Harina'),
('Azúcar'), ('Cacao'), ('Huevos'), ('Lentejas'), ('Verduras mixtas'), ('Especias'), ('Aguacate'), ('Tostadas'), ('Banano'), ('Fresas'),
('Yogurt'), ('Leche'), ('Manzanas'), ('Canela'), ('Pollo'), ('Pimienta'), ('Sal'), ('Aceite de oliva'), ('Ajo'), ('Albahaca'),
('Orégano'), ('Mantequilla'), ('Cebolla'), ('Zanahoria'), ('Apio'), ('Arroz'), ('Vino blanco'), ('Champiñones'), ('Espinacas'), ('Jengibre'),
('Agua de coco'), ('Galletas de vainilla'), ('Queso crema'), ('Frijoles'), ('Chiles'), ('Carne molida'), ('Tortillas de maíz'), ('Repollo'), ('Salmón'), ('Hierbas finas'),
('Queso parmesano'), ('Lechuga romana'), ('Crutones'), ('Pavo'), ('Pan'), ('Mermelada'), ('Proteína en polvo'), ('Chile'), ('Curry en polvo'), ('Leche de coco'),
('Plátanos maduros'), ('Bicarbonato de sodio'), ('Nueces'), ('Vinagreta'), ('Pescado blanco'), ('Pan rallado'), ('Papa'), ('Sirope'), ('Huevo'), ('Yogurt griego'),
('Fresa'), ('Piña'), ('Mango'), ('Crema de leche'), ('Galletas de café'), ('Mascarpone'), ('Bizcochos de soletilla'), ('Café espresso'), ('Jamón serrano'), ('Nuez moscada'),
('Pan viejo'), ('Caldo de verduras'), ('Bolsa de té'), ('Miel'), ('Avena'), ('Semillas de chía'), ('Moras'), ('Frambuesas'), ('Manzana'), ('Naranja'),
('Pimiento'), ('Puerro'), ('Salsa de soya'), ('Jengibre fresco'), ('Frijoles negros'), ('Tocineta'), ('Pan de ajo'), ('Parmesano rallado'), ('Tomillo'), ('Romero');

-- 3. Datos para la tabla RECETAS (100 registros)
INSERT INTO RECETAS (titulo, instrucciones, tiempo_preparacion, dificultad, ID_CATEGORIA) VALUES
('Pasta con pesto', 'Cocina la pasta y mezcla con pesto, tomates cherry y queso rallado.', 20, 'Fácil', 1),
('Ensalada de quinoa', 'Mezcla quinoa cocida con pepino, tomate, cebolla roja y aderezo de limón.', 15, 'Fácil', 2),
('Brownies de chocolate', 'Mezcla harina, azúcar, cacao y huevos. Hornea por 25 minutos.', 40, 'Media', 3),
('Sopa de lentejas', 'Cocina las lentejas con verduras y especias hasta que estén suaves.', 50, 'Media', 4),
('Huevos revueltos con aguacate', 'Prepara los huevos revueltos y sírvelos con aguacate en rodajas y tostadas.', 10, 'Fácil', 5),
('Tarta de manzana', 'Prepara la masa, rellena con manzanas, canela y azúcar, y hornea.', 60, 'Difícil', 3),
('Batido de frutas', 'Licúa banano, fresas, yogurt y leche.', 5, 'Muy fácil', 2),
('Pollo a la parrilla con vegetales', 'Marina el pollo y los vegetales. Cocínalos a la parrilla hasta que estén dorados.', 30, 'Fácil', 2),
('Lasaña de carne', 'Prepara la salsa bechamel, la salsa de carne y arma las capas de lasaña. Hornea.', 90, 'Difícil', 4),
('Panqueques de arándanos', 'Mezcla la masa de panqueques y añade arándanos. Cocina en sartén.', 25, 'Fácil', 5),
('Tacos de pescado', 'Fríe el pescado sazonado. Sírvelo en tortillas de maíz con repollo y salsa.', 35, 'Media', 1),
('Crema de calabaza', 'Cocina la calabaza con cebolla y caldo de verduras. Licúa y sirve.', 45, 'Fácil', 2),
('Galletas de avena', 'Mezcla avena, harina, azúcar, huevo y pasas. Hornea.', 20, 'Fácil', 3),
('Arroz con pollo', 'Sofríe el pollo con arroz y verduras. Cocina con caldo de pollo.', 60, 'Media', 4),
('Omelette de espinacas y queso', 'Bate los huevos y mezcla con espinacas y queso. Cocina en sartén.', 15, 'Fácil', 5),
('Risotto de champiñones', 'Sofríe el arroz con vino blanco. Agrega caldo poco a poco y los champiñones.', 45, 'Difícil', 4),
('Smoothie verde', 'Licúa espinacas, manzana, jengibre y agua de coco.', 5, 'Muy fácil', 2),
('Cheesecake de fresa', 'Prepara la base de galleta y la mezcla de queso crema. Hornea y decora con fresas.', 120, 'Difícil', 3),
('Chili con carne', 'Cocina la carne molida con frijoles, tomates y chiles. Cocina a fuego lento.', 75, 'Media', 4),
('Tostadas francesas', 'Remoja el pan en una mezcla de huevo y leche. Dora en mantequilla.', 15, 'Fácil', 5),
('Salmón al horno con hierbas', 'Sazona el salmón con hierbas, aceite de oliva y ajo. Hornea.', 25, 'Fácil', 2),
('Pizza casera', 'Prepara la masa. Agrega salsa de tomate, queso y tus ingredientes favoritos. Hornea.', 40, 'Media', 4),
('Ensalada César', 'Lava la lechuga romana. Mezcla con crutones, queso parmesano y aderezo César.', 10, 'Muy fácil', 1),
('Sándwich de pavo y aguacate', 'Coloca rebanadas de pavo, aguacate y lechuga entre dos panes.', 5, 'Muy fácil', 1),
('Tostadas con mermelada', 'Tuesta el pan y úntale mermelada de tu elección.', 3, 'Muy fácil', 5),
('Batido de proteína', 'Mezcla proteína en polvo, leche y una fruta de tu elección.', 5, 'Muy fácil', 2),
('Huevos a la mexicana', 'Pica el tomate, la cebolla y el chile. Sofríelos y agrega los huevos batidos.', 15, 'Fácil', 5),
('Pollo al curry', 'Sofríe el pollo con curry en polvo, leche de coco y verduras.', 45, 'Media', 4),
('Pan de banana', 'Mezcla plátanos machacados, harina, azúcar y huevo. Hornea.', 60, 'Media', 3),
('Gazpacho', 'Licúa tomate, pepino, pimiento, cebolla, ajo y aceite de oliva. Enfría.', 20, 'Fácil', 2),
('Tarta de queso', 'Mezcla queso crema, azúcar y huevo. Hornea.', 50, 'Media', 3),
('Ensalada de pasta', 'Cocina la pasta y mezcla con vegetales frescos y aderezo de vinagreta.', 25, 'Fácil', 1),
('Pescado frito', 'Sazona y empaniza el pescado. Fríelo en aceite caliente.', 20, 'Fácil', 1),
('Tortilla española', 'Fríe papas y cebolla. Agrega los huevos batidos y cocina.', 40, 'Media', 4),
('Waffles', 'Prepara la masa y cocina en una wafflera. Sirve con sirope.', 20, 'Fácil', 5),
('Curry de lentejas', 'Cocina las lentejas con leche de coco, tomate y especias.', 45, 'Media', 2),
('Helado casero de vainilla', 'Mezcla crema, leche, azúcar y vainilla. Congela.', 180, 'Difícil', 3),
('Patatas bravas', 'Fríe las papas y sírvelas con salsa de tomate picante y mayonesa.', 30, 'Media', 4),
('Crema de espárragos', 'Cocina los espárragos. Licúa con un poco de crema y caldo de verduras.', 25, 'Fácil', 2),
('Muffins de chocolate', 'Mezcla harina, azúcar, cacao, huevos y chispas de chocolate. Hornea.', 30, 'Fácil', 3),
('Pollo asado', 'Sazona un pollo entero y hornéalo hasta que esté dorado.', 90, 'Difícil', 4),
('Ensalada de atún', 'Mezcla atún enlatado con mayonesa, cebolla, apio y pepinillos.', 10, 'Muy fácil', 1),
('Smoothie de mango y piña', 'Licúa mango, piña y jugo de naranja.', 5, 'Muy fácil', 2),
('Budín de pan', 'Remoja pan viejo en leche, huevos y azúcar. Hornea.', 60, 'Media', 3),
('Frijoles refritos', 'Machaca frijoles cocidos y fríelos con cebolla y ajo.', 20, 'Fácil', 4),
('Avena con frutas', 'Cocina la avena y sírvela con frutas frescas y miel.', 15, 'Muy fácil', 5),
('Pescado al vapor', 'Cocina el pescado al vapor con jengibre y salsa de soya.', 25, 'Fácil', 2),
('Sopa de tomate', 'Cocina tomates con cebolla y ajo. Licúa y sirve con crema.', 30, 'Fácil', 4),
('Tiramisú', 'Moja las galletas en café, alterna con una mezcla de queso mascarpone y huevos. Refrigera.', 30, 'Difícil', 3),
('Croquetas de jamón', 'Prepara una bechamel con jamón picado. Arma las croquetas y fríelas.', 50, 'Difícil', 4),
('Guacamole', 'Machaca aguacates. Mezcla con tomate, cebolla, cilantro, jugo de limón y sal.', 10, 'Muy fácil', 1),
('Batido de banana y avena', 'Licúa banana, avena, leche y un toque de canela.', 5, 'Muy fácil', 5),
('Crepes de Nutella y banana', 'Prepara la masa de crepes. Rellena con Nutella y rodajas de banana.', 20, 'Fácil', 3),
('Sopa de verduras', 'Cocina verduras surtidas en caldo. Sazona con sal y pimienta.', 30, 'Fácil', 2),
('Arroz frito', 'Saltea arroz cocido con verduras, huevo y salsa de soya.', 25, 'Fácil', 4),
('Hamburguesa casera', 'Forma las hamburguesas con carne molida. Cocina y sirve en pan con tus ingredientes favoritos.', 30, 'Media', 4),
('Ensalada de pollo', 'Mezcla pollo desmenuzado con mayonesa, apio y cebolla. Sirve en pan.', 15, 'Fácil', 1),
('Smoothie de fresa y mango', 'Licúa fresas, mango, yogurt y un poco de jugo de naranja.', 5, 'Muy fácil', 2),
('Tostada con aguacate y huevo', 'Tuesta pan. Coloca aguacate machacado y un huevo frito o cocido encima.', 10, 'Fácil', 5),
('Pan de ajo', 'Unta mantequilla de ajo en pan. Hornea hasta que esté dorado.', 15, 'Fácil', 4),
('Pasta a la carbonara', 'Cocina pasta y mezcla con una salsa de huevo, queso, tocineta y pimienta.', 25, 'Difícil', 4),
('Ensalada de frutas', 'Pica una variedad de frutas y mézclalas en un tazón.', 10, 'Muy fácil', 2),
('Rollos de canela', 'Prepara la masa, rellena con canela y azúcar. Hornea y cubre con glaseado.', 60, 'Difícil', 3),
('Puré de papa', 'Hierve papas. Machácalas y mezcla con mantequilla, leche, sal y pimienta.', 20, 'Fácil', 4),
('Huevos benedictinos', 'Prepara la salsa holandesa. Pocha los huevos y sirve sobre pan tostado con jamón.', 25, 'Difícil', 5),
('Sopa de cebolla francesa', 'Sofríe cebollas en mantequilla. Agrega caldo y cocina. Cubre con pan y queso.', 50, 'Media', 4),
('Tacos de carne asada', 'Asa la carne. Pica y sirve en tortillas de maíz con cilantro y cebolla.', 30, 'Fácil', 1),
('Sopa de fideos de pollo', 'Cocina fideos y pollo en caldo de pollo con verduras.', 35, 'Fácil', 4),
('Pastel de zanahoria', 'Mezcla harina, zanahoria rallada, especias y nueces. Hornea y cubre con betún de queso crema.', 60, 'Media', 3),
('Ensalada de garbanzos', 'Mezcla garbanzos con pepino, tomate, cebolla y un aderezo de limón y hierbas.', 15, 'Fácil', 2),
('Batido de chocolate', 'Licúa cacao en polvo, leche, azúcar y hielo.', 5, 'Muy fácil', 2),
('Galletas con chispas de chocolate', 'Prepara la masa de galletas con chispas de chocolate. Hornea.', 20, 'Fácil', 3),
('Pudín de chía', 'Mezcla semillas de chía con leche y azúcar. Refrigera toda la noche. Sirve con frutas.', 10, 'Muy fácil', 5),
('Salsa de tomate casera', 'Cocina tomates, ajo, cebolla y orégano. Licúa y cocina a fuego lento.', 45, 'Fácil', 4),
('Salmón con espárragos al vapor', 'Cocina el salmón y los espárragos al vapor. Sazona con sal y pimienta.', 20, 'Fácil', 2),
('Rollos de sushi', 'Prepara el arroz para sushi. Rellena con pescado crudo y vegetales.', 45, 'Difícil', 1),
('Sopa de pollo con vegetales', 'Cocina el pollo con verduras en caldo. Sazona y sirve.', 40, 'Fácil', 4),
('Sándwich de queso a la parrilla', 'Coloca queso entre dos rebanadas de pan. Derrítelo en una sartén con mantequilla.', 10, 'Muy fácil', 1),
('Brownie de chocolate blanco', 'Mezcla chocolate blanco derretido con harina, huevos y azúcar. Hornea.', 35, 'Media', 3),
('Tortilla de papa', 'Corta papas en rodajas finas. Fríelas. Bate huevos y mezcla. Cocina.', 45, 'Media', 4),
('Smoothie de proteínas y bayas', 'Licúa proteína en polvo, bayas congeladas, leche de almendras y espinacas.', 5, 'Muy fácil', 2),
('Tostadas con mermelada y crema de cacahuete', 'Tuesta pan, úntale crema de cacahuete y mermelada.', 5, 'Muy fácil', 5),
('Pollo al ajillo', 'Sofríe el pollo con ajo, vino blanco y perejil.', 30, 'Fácil', 4),
('Crema de brócoli', 'Cocina el brócoli, licúa y mezcla con crema y caldo.', 25, 'Fácil', 2),
('Galletas de chispas de chocolate', 'Mezcla harina, azúcar, huevos y chispas de chocolate. Hornea.', 20, 'Fácil', 3),
('Sopa de pasta con albóndigas', 'Cocina las albóndigas y la pasta en caldo de res.', 45, 'Media', 4),
('Ensalada de espinacas y fresas', 'Mezcla espinacas frescas con fresas, nueces y aderezo de vinagreta.', 15, 'Muy fácil', 2),
('Batido de café', 'Licúa café, leche, azúcar y hielo.', 5, 'Muy fácil', 5),
('Pan de molde casero', 'Prepara la masa con levadura, harina, agua, sal y azúcar. Amasa, deja leudar y hornea.', 120, 'Difícil', 4),
('Muffins de arándanos', 'Mezcla la masa de muffins con arándanos. Hornea.', 30, 'Fácil', 3),
('Sopa de pollo y fideos', 'Cocina fideos y pollo en caldo de pollo con verduras.', 35, 'Fácil', 4),
('Pastel de chocolate', 'Prepara la masa con harina, cacao, azúcar, huevos y leche. Hornea y cubre con glaseado de chocolate.', 60, 'Media', 3),
('Ensalada de pollo y aguacate', 'Mezcla pollo desmenuzado, aguacate, tomate y cebolla con aderezo.', 15, 'Fácil', 1),
('Smoothie de mango y banana', 'Licúa mango, banana, yogurt y jugo de naranja.', 5, 'Muy fácil', 2),
('Tostada con huevo y tocineta', 'Tuesta pan, fríe tocineta y huevos. Colócalos sobre el pan.', 10, 'Fácil', 5),
('Pasta con atún', 'Cocina la pasta y mezcla con atún, mayonesa y cebolla.', 15, 'Fácil', 1),
('Rollitos de primavera', 'Rellena hojas de masa con vegetales, carne o pollo. Fríelos en aceite.', 40, 'Media', 1),
('Curry de garbanzos', 'Cocina garbanzos con cebolla, jengibre, ajo y pasta de curry.', 30, 'Fácil', 2),
('Tarta de limón', 'Prepara la base de galletas y mezcla la crema de limón. Refrigera.', 30, 'Difícil', 3),
('Caldo de pollo', 'Hierve pollo y vegetales en agua. Sazona con sal y hierbas.', 60, 'Fácil', 4),
('Huevos pochados', 'Rompe el huevo en agua hirviendo con vinagre. Cocina por 3 minutos.', 5, 'Difícil', 5),
('Pan de ajo con queso', 'Corta el pan. Rellena con mantequilla de ajo y queso. Hornea.', 15, 'Fácil', 4);

-- 4. Datos para la tabla de unión (100 relaciones para las 100 recetas)
INSERT INTO RECETAS_INGREDIENTES (ID_RECETA, ID_INGREDIENTE, cantidad) VALUES
(1, 1, '200g'), (1, 2, '50g'), (1, 3, '100g'), (1, 4, '30g'), (2, 5, '1 taza'),
(2, 6, '1/2 unidad'), (2, 7, '1 unidad'), (2, 8, '1/4 unidad'), (2, 9, '1 unidad'), (3, 10, '150g'),
(3, 11, '200g'), (3, 12, '50g'), (3, 13, '2 unidades'), (4, 14, '1 taza'), (4, 15, '150g'),
(4, 16, 'al gusto'), (5, 13, '2 unidades'), (5, 17, '1 unidad'), (5, 18, '2 rebanadas'), (6, 10, '200g'),
(6, 11, '150g'), (6, 23, '3 unidades'), (6, 24, '1/2 cdta'), (7, 19, '1 unidad'), (7, 20, '100g'),
(8, 25, '500g'), (8, 26, 'al gusto'), (8, 27, 'al gusto'), (8, 28, '2 cdas'), (9, 29, '2 dientes'),
(9, 30, '150g'), (9, 31, '100g'), (9, 32, '30g'), (10, 10, '200g'), (10, 11, '50g'),
(11, 25, '300g'), (11, 33, '1 unidad'), (11, 34, '1 unidad'), (11, 35, '1 unidad'), (12, 33, '1 unidad'),
(12, 29, '2 dientes'), (13, 36, '1 taza'), (13, 37, '1/2 taza'), (13, 38, '200g'), (14, 39, '50g'),
(14, 27, 'al gusto'), (15, 13, '2 unidades'), (15, 39, '50g'), (15, 4, '30g'), (16, 36, '1 taza'),
(16, 37, '1/2 taza'), (16, 38, '200g'), (17, 39, '50g'), (17, 23, '1 unidad'), (17, 40, '1/2 cdta'),
(18, 41, '250g'), (18, 42, '1 paquete'), (18, 43, '250g'), (19, 44, '1 taza'), (19, 45, 'al gusto'),
(20, 13, '2 unidades'), (20, 22, '1 taza'), (20, 32, '1 cda'), (21, 46, '300g'), (21, 47, 'al gusto'),
(22, 48, '1 unidad'), (22, 49, '100g'), (22, 50, '50g'), (23, 51, '1 unidad'), (23, 52, '100g'),
(24, 53, 'al gusto'), (24, 54, '2 rebanadas'), (24, 55, '1/2 unidad'), (25, 54, '3 rebanadas'), (25, 55, '100g'),
(26, 56, 'al gusto'), (26, 57, '1 scoop'), (26, 22, '200ml'), (27, 7, '1 unidad'), (27, 33, '1/2 unidad'),
(28, 25, '300g'), (28, 58, '1 cda'), (28, 59, '1 cdta'), (29, 60, 'al gusto'), (29, 61, '2 unidades'),
(30, 7, '3 unidades'), (30, 6, '1 unidad'), (30, 91, '1/2 unidad'), (31, 43, '200g'), (31, 11, '100g'),
(32, 1, '200g'), (32, 15, '100g'), (33, 65, '300g'), (33, 26, 'al gusto'), (34, 67, '4 unidades'),
(34, 33, '1 unidad'), (34, 13, '4 unidades'), (35, 10, '200g'), (35, 13, '2 unidades'), (35, 22, '100ml'),
(36, 14, '1 taza'), (36, 60, 'al gusto'), (36, 7, '2 unidades'), (37, 75, '200g'), (37, 22, '150ml'),
(38, 67, '500g'), (38, 7, '1 unidad'), (38, 68, '2 cdas'), (39, 6, '1 unidad'), (39, 81, '1 taza'),
(40, 10, '150g'), (40, 11, '150g'), (40, 12, '50g'), (41, 25, '1 unidad'), (41, 26, 'al gusto'),
(42, 46, '150g'), (42, 6, '1 unidad'), (43, 72, '1 unidad'), (43, 73, '1 unidad'), (44, 10, '150g'),
(44, 22, '1 taza'), (44, 13, '2 unidades'), (45, 44, '1 taza'), (45, 33, '1/2 unidad'), (46, 85, '1 taza'),
(46, 70, 'al gusto'), (47, 65, '300g'), (47, 9, '1 unidad'), (48, 7, '1 unidad'), (48, 33, '1/2 unidad'),
(49, 76, '150g'), (49, 77, '100g'), (49, 78, '50g'), (50, 89, '100g'), (50, 32, '50g'),
(51, 17, '2 unidades'), (51, 7, '1 unidad'), (51, 33, '1/4 unidad'), (51, 9, 'al gusto'), (52, 19, '1 unidad'),
(52, 85, '1/2 taza'), (52, 22, '200ml'), (52, 24, '1 pizca'), (53, 10, '100g'), (53, 11, '50g'),
(53, 12, '20g'), (53, 19, '1 unidad'), (53, 22, '100ml'), (54, 15, '300g'), (54, 82, '500ml'),
(54, 27, 'al gusto'), (55, 36, '1 taza'), (55, 15, '100g'), (55, 27, 'al gusto'), (55, 93, '2 cdas'),
(56, 46, '300g'), (56, 12, '50g'), (56, 11, '10g'), (57, 20, '100g'), (57, 72, '100g'),
(58, 54, '2 rebanadas'), (58, 17, '1 unidad'), (58, 13, '1 unidad'), (59, 29, '2 dientes'), (59, 54, '2 rebanadas'),
(60, 1, '200g'), (60, 13, '2 unidades'), (60, 96, '50g'), (60, 26, 'al gusto'), (61, 10, '100g'),
(61, 11, '50g'), (61, 24, '1/2 cdta'), (62, 67, '200g'), (62, 32, '20g'), (63, 13, '2 unidades'),
(63, 68, 'al gusto'), (63, 70, 'al gusto'), (64, 33, '1 unidad'), (64, 82, '1l'), (64, 51, '50g'),
(65, 46, '300g'), (65, 47, 'al gusto'), (65, 33, '1/2 unidad'), (66, 25, '300g'), (66, 15, '100g'),
(66, 27, 'al gusto'), (67, 10, '100g'), (67, 24, '1 cdta'), (67, 11, '50g'), (68, 5, '100g'),
(68, 6, '1/2 unidad'), (68, 7, '1 unidad'), (68, 9, 'al gusto'), (69, 12, '50g'), (69, 22, '200ml'),
(70, 10, '150g'), (70, 11, '150g'), (70, 12, '50g'), (71, 86, '50g'), (71, 22, '1 taza'),
(72, 7, '3 unidades'), (72, 29, '1 diente'), (72, 33, '1/2 unidad'), (73, 46, '300g'), (73, 39, '50g'),
(74, 1, '200g'), (74, 46, '1 lata'), (74, 32, '2 cdas'), (75, 10, '200g'), (75, 11, '150g'),
(75, 13, '2 unidades'), (75, 22, '100ml'), (76, 43, '200g'), (76, 11, '100g'), (77, 67, '500g'),
(77, 33, '1 unidad'), (77, 13, '4 unidades'), (78, 57, '1 scoop'), (78, 87, '1 taza'), (79, 54, '2 rebanadas'),
(79, 56, 'al gusto'), (79, 88, 'al gusto'), (80, 25, '300g'), (80, 29, '2 dientes'), (81, 6, '1 unidad'),
(81, 7, '1 unidad'), (81, 9, '1/2 unidad'), (82, 10, '150g'), (82, 11, '100g'), (82, 12, '50g'),
(83, 36, '2 tazas'), (83, 37, '1/2 taza'), (83, 38, '200g'), (84, 39, '150g'), (84, 91, '50g'),
(85, 25, '500g'), (85, 15, '100g'), (86, 20, '100g'), (86, 9, '1/2 unidad'), (87, 10, '150g'),
(87, 11, '50g'), (87, 12, '20g'), (87, 95, '50g'), (88, 86, '50g'), (88, 20, '100g'),
(89, 25, '500g'), (89, 15, '100g'), (89, 27, 'al gusto'), (90, 70, '100g'), (90, 71, '50g'),
(91, 10, '200g'), (91, 11, '150g'), (91, 12, '50g'), (92, 10, '150g'), (92, 11, '100g'),
(93, 20, '100g'), (93, 72, '100g'), (93, 21, '100ml'), (94, 7, '1 unidad'), (94, 33, '1/2 unidad'),
(95, 1, '200g'), (95, 46, '1 lata'), (96, 75, '200g'), (96, 77, '150g'), (97, 85, '100g'),
(97, 20, '50g'), (97, 63, '50g'), (98, 14, '1 taza'), (98, 60, '100ml'), (99, 10, '200g'),
(99, 11, '150g'), (99, 12, '50g'), (100, 25, '500g'), (100, 32, '50g');